import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "worker/dist/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `pnpm storm:build` (git-ignored bundle).
    "public/storm-worker.js",
    // Agent worktrees (each is its own copy of the repo).
    ".claude/**",
  ]),
]);

export default eslintConfig;
