// Generated by `pnpm content:index` from content/bracer/. Do not edit by hand; `pnpm content:check` fails if it is stale.
import track_canyon from '../../content/bracer/tracks/canyon/track.json';
import track_mempool_loop from '../../content/bracer/tracks/mempool-loop/track.json';
import track_spiral from '../../content/bracer/tracks/spiral/track.json';
import track_void from '../../content/bracer/tracks/void/track.json';
import ship_manta from '../../content/bracer/ships/manta/ship.json';
import ship_needle from '../../content/bracer/ships/needle/ship.json';
import ship_wedge from '../../content/bracer/ships/wedge/ship.json';

export const TRACK_PACKS: { slug: string; json: unknown }[] = [
  { slug: 'canyon', json: track_canyon },
  { slug: 'mempool-loop', json: track_mempool_loop },
  { slug: 'spiral', json: track_spiral },
  { slug: 'void', json: track_void },
];
export const SHIP_PACKS: { slug: string; json: unknown }[] = [
  { slug: 'manta', json: ship_manta },
  { slug: 'needle', json: ship_needle },
  { slug: 'wedge', json: ship_wedge },
];
