/**
 * Content-pack tooling shared by `pnpm content:index`, `pnpm content:check` and the tests.
 * Packs live in content/bracer/{tracks,ships}/<slug>/; see CONTRIBUTING.md and src/lib/content/schema.ts.
 */
import fs from 'node:fs';
import path from 'node:path';
import { checkPackFiles, LIMITS, validateShipPack, validateTrackPack } from '../src/lib/content/schema';
import { trackDefFromPack } from '../src/lib/hyper/packs';
import { buildTrack } from '../src/lib/hyper/track';

export const ROOT = path.resolve(__dirname, '..');
export const INDEX_FILE = 'src/content/bracer.generated.ts';

const dirs = (p: string) => (fs.existsSync(p) ? fs.readdirSync(p, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name).sort() : []);

export function listPacks(root = ROOT) {
  const base = path.join(root, 'content/bracer');
  return { tracks: dirs(path.join(base, 'tracks')), ships: dirs(path.join(base, 'ships')) };
}

/** The generated registry: static JSON imports, so webpack and Turbopack bundle every pack at build time. */
export function renderIndex(root = ROOT): string {
  const { tracks, ships } = listPacks(root);
  const id = (s: string) => s.replace(/-/g, '_');
  const lines = [
    '// Generated by `pnpm content:index` from content/bracer/. Do not edit by hand; `pnpm content:check` fails if it is stale.',
    ...tracks.map((s) => `import track_${id(s)} from '../../content/bracer/tracks/${s}/track.json';`),
    ...ships.map((s) => `import ship_${id(s)} from '../../content/bracer/ships/${s}/ship.json';`),
    '',
    `export const TRACK_PACKS: { slug: string; json: unknown }[] = [${tracks.map((s) => `\n  { slug: '${s}', json: track_${id(s)} },`).join('')}\n];`,
    `export const SHIP_PACKS: { slug: string; json: unknown }[] = [${ships.map((s) => `\n  { slug: '${s}', json: ship_${id(s)} },`).join('')}\n];`,
    '',
  ];
  return lines.join('\n');
}

function filesOf(dir: string): Record<string, number> {
  const out: Record<string, number> = {};
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name === '.DS_Store') continue;
    out[e.isDirectory() ? `${e.name}/` : e.name] = e.isDirectory() ? 0 : fs.statSync(path.join(dir, e.name)).size;
  }
  return out;
}

function readJson(file: string, errors: string[]): unknown {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch (e) {
    errors.push(`${path.relative(ROOT, file)}: is not valid JSON (${(e as Error).message})`);
    return undefined;
  }
}

/** Validates every pack under `root`. Returns human-readable errors (empty = all good). */
export function checkAll(root = ROOT, opts: { index?: boolean } = {}): { errors: string[]; summary: string[] } {
  const errors: string[] = [];
  const summary: string[] = [];
  const { tracks, ships } = listPacks(root);
  if (!tracks.length) errors.push('content/bracer/tracks: no track packs found');
  if (!ships.length) errors.push('content/bracer/ships: no ship packs found');
  for (const slug of tracks) {
    const dir = path.join(root, 'content/bracer/tracks', slug);
    const rel = `content/bracer/tracks/${slug}/track.json`;
    const fe = checkPackFiles('track', slug, filesOf(dir));
    errors.push(...fe);
    if (!fs.existsSync(path.join(dir, 'track.json'))) continue;
    const json = readJson(path.join(dir, 'track.json'), errors);
    if (json === undefined) continue;
    const r = validateTrackPack(json, rel);
    if (!r.ok) {
      errors.push(...r.errors);
      continue;
    }
    // Build it: the spline must close and the lap length must be sane.
    try {
      const tr = buildTrack(trackDefFromPack(slug, r.value));
      const [lo, hi] = LIMITS.lapLen;
      if (!(tr.len >= lo && tr.len <= hi)) errors.push(`${rel}: lap is ${Math.round(tr.len)} m; it must be ${lo}-${hi} m (spread the points out or in)`);
      const seam = Math.hypot(tr.px[0] - tr.px[tr.n - 1], tr.py[0] - tr.py[tr.n - 1], tr.pz[0] - tr.pz[tr.n - 1]);
      if (!(seam < 6)) errors.push(`${rel}: the track does not close cleanly (seam ${seam.toFixed(1)} m)`);
      if (tr.bounds.minY < -50) errors.push(`${rel}: the track dips below the ground (min height ${tr.bounds.minY.toFixed(0)} m)`);
      if (!fe.length) summary.push(`track ${slug}: ${r.value.name} by ${r.value.author} (${r.value.licence}), ${Math.round(tr.len)} m`);
    } catch (e) {
      errors.push(`${rel}: failed to build (${(e as Error).message})`);
    }
  }
  for (const slug of ships) {
    const dir = path.join(root, 'content/bracer/ships', slug);
    const rel = `content/bracer/ships/${slug}/ship.json`;
    const files = filesOf(dir);
    let head: Uint8Array | undefined;
    if ('model.glb' in files) head = new Uint8Array(fs.readFileSync(path.join(dir, 'model.glb')).subarray(0, 4));
    const fe = checkPackFiles('ship', slug, files, head);
    errors.push(...fe);
    if (!fs.existsSync(path.join(dir, 'ship.json'))) continue;
    const json = readJson(path.join(dir, 'ship.json'), errors);
    if (json === undefined) continue;
    const r = validateShipPack(json, rel);
    if (!r.ok) {
      errors.push(...r.errors);
      continue;
    }
    if (r.value.model && !('model.glb' in files)) errors.push(`${rel}: says "model": "model.glb" but there is no model.glb next to it`);
    if (!fe.length) summary.push(`ship ${slug}: ${r.value.name} by ${r.value.author} (${r.value.licence})`);
  }
  // CC-BY packs must ship a CREDITS.md too.
  for (const [kind, list] of [['tracks', tracks], ['ships', ships]] as const) {
    for (const slug of list) {
      const dir = path.join(root, 'content/bracer', kind, slug);
      const main = path.join(dir, kind === 'tracks' ? 'track.json' : 'ship.json');
      if (!fs.existsSync(main)) continue;
      try {
        const j = JSON.parse(fs.readFileSync(main, 'utf8')) as { licence?: string };
        if (j.licence === 'CC-BY-4.0' && !fs.existsSync(path.join(dir, 'CREDITS.md'))) errors.push(`content/bracer/${kind}/${slug}: CC-BY-4.0 packs need a CREDITS.md naming the original author and source`);
      } catch {
        /* reported above */
      }
    }
  }
  if (opts.index !== false) {
    const want = renderIndex(root);
    const file = path.join(root, INDEX_FILE);
    const have = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
    if (have !== want) errors.push(`${INDEX_FILE}: is out of date; run \`pnpm content:index\` and commit the result`);
  }
  return { errors, summary };
}
